In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s.dtypes

dtype('int64')

In [ ]:
s.values

array([10, 20, 30, 40, 50])

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
print (s.name)

None

In [ ]:
s.name="numbers"
s

0    10
1    20
2    30
3    40
4    50
Name: numbers, dtype: int64

In [ ]:
#Indixing

print(s[0])
s[0:2]

10

0    10
1    20
Name: numbers, dtype: int64

In [ ]:
#iloc ->  location based indexing

s.iloc[3]
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: int64

In [ ]:
s.index = ["apple" , "banana", "grapes", "oranges", "strawberry" ]
s

apple         10
banana        20
grapes        30
oranges       40
strawberry    50
Name: numbers, dtype: int64

In [ ]:
#loc ->  lable based indexing.

s.loc["apple"]
s.loc[["apple","oranges"]]

apple      10
oranges    40
Name: numbers, dtype: int64

In [ ]:
#in label based indexing your start as well as stop value both are included in the output
s['banana':'orange']

banana    20
grapes    30
Name: numbers, dtype: int64

In [ ]:
fruit_protein = {

"Avocado" : 2.0,
"Guava": 2.6,
"Blackberries": 2.0,
"Oranges": 0.9,
"Banana": 1.1,
"Apples": 0.3,
"Kiwi": 1.1,
"Pomegranate": 1.7,
"Mango": 0.8,
"Cherries": 1.0

}

In [ ]:
s2 = pd.Series(fruit_protein, name = "Protein")
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [ ]:
# conditional selection:

s2[s2>1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: Protein, dtype: float64

In [ ]:
#Logical operators
s2[(s2>0.5) & (s2<=2.0)]

Avocado         2.0
Blackberries    2.0
Oranges         0.9
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [ ]:
s2[(s2>0.5) | (s2 <= 2)]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [ ]:
# not operation:
s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

In [ ]:
# Modyfying the series:
s2 ["Mango"] = 2.8
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
Cherries        1.0
Name: Protein, dtype: float64

In [ ]:
import numpy as np

In [ ]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
s.notnull().sum()

np.int64(5)

In [ ]:
import numpy as np
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
s.notnull().sum()

np.int64(5)

In [ ]:
# DataFrame:

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [ ]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [ ]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [ ]:
df.head(2)
df.tail(2)
df.tail(3)

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [ ]:
#loc and i loc
df.iloc[2:4]

      Name   Age Department   Salary
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0

In [ ]:
df.loc[1:3, ["Age", "Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [ ]:
df[["Age", "Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [ ]:
df.drop("Age", axis = 1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [ ]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [ ]:
df.shape

(6, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [ ]:
df ["Salary"]

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4        NaN
5    50000.0
Name: Salary, dtype: float64

In [ ]:
#Broadcasting
df["Salary"] = df["Salary"] + 5000

In [ ]:
df ["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [ ]:
# Renaming columns:

df.rename(columns ={ "Department" : "Dept"}, inplace=True)

In [ ]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [ ]:
df ["Dept"]. unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [ ]:
df ["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [ ]:
df["Promoted Salary"] = df["Salary"] * 10
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

#**Data Cleaning**

In [ ]:
# Data Cleaning
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [ ]:
df.dropna()

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [ ]:
df.dropna(how = "any")  # any row that had any null value

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [ ]:
df.dropna(how = "all") #if all the values in any row are null then we drop

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [ ]:
df.fillna(0)

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   0.0       IT  67000.0         670000.0
4      Eve  29.0       HR      0.0              0.0
5    Alice  25.0       HR  55000.0         550000.0

In [ ]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [ ]:
df["Age"].fillna(method= "ffill")

/tmp/ipykernel_2595/1213299537.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method= "ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Age"].fillna(method= "bfill")

/tmp/ipykernel_2595/3764334975.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method= "bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Name"].replace("Charlie", "Rose", inplace = True)
df

/tmp/ipykernel_2595/3535215102.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].replace("Charlie", "Rose", inplace = True)

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  55000.0         550000.0

In [ ]:
df_dup = df[df.duplicated()]
df_dup

    Name   Age Dept   Salary  Promoted Salary
5  Alice  25.0   HR  55000.0         550000.0

In [ ]:
df_dup = df[df.duplicated(keep = "first" )]
df_dup

    Name   Age Dept   Salary  Promoted Salary
5  Alice  25.0   HR  55000.0         550000.0

In [ ]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  55000.0         550000.0

In [ ]:
df = df.drop_duplicates()
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN

In [ ]:
#invalied values
# Lambda -> python

df ["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 60000 else x)
df

/tmp/ipykernel_2595/4282384991.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df ["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 60000 else x)

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0          55000.0
1    Bob  30.0       IT  65000.0          65000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [ ]:
#This is just a demod it wont work we don't have dataset for ths

name = "alice_fernandes"
df[["first name", "last name"]] = df["name"].str.split("_")

KeyError: 'name'

In [ ]:
#apply and lambda